//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceCalc.ConsoleClient.ServiceReferenceDistCalc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Point", Namespace="http://schemas.datacontract.org/2004/07/DistanceCalcSoapService")]
    [System.SerializableAttribute()]
    public partial class Point : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDistCalc.IDistCalc")]
    public interface IDistCalc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistCalc/distance", ReplyAction="http://tempuri.org/IDistCalc/distanceResponse")]
        double distance(DistanceCalc.ConsoleClient.ServiceReferenceDistCalc.Point startPoint, DistanceCalc.ConsoleClient.ServiceReferenceDistCalc.Point endPoint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistCalc/distance", ReplyAction="http://tempuri.org/IDistCalc/distanceResponse")]
        System.Threading.Tasks.Task<double> distanceAsync(DistanceCalc.ConsoleClient.ServiceReferenceDistCalc.Point startPoint, DistanceCalc.ConsoleClient.ServiceReferenceDistCalc.Point endPoint);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDistCalcChannel : DistanceCalc.ConsoleClient.ServiceReferenceDistCalc.IDistCalc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DistCalcClient : System.ServiceModel.ClientBase<DistanceCalc.ConsoleClient.ServiceReferenceDistCalc.IDistCalc>, DistanceCalc.ConsoleClient.ServiceReferenceDistCalc.IDistCalc {
        
        public DistCalcClient() {
        }
        
        public DistCalcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DistCalcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistCalcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistCalcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double distance(DistanceCalc.ConsoleClient.ServiceReferenceDistCalc.Point startPoint, DistanceCalc.ConsoleClient.ServiceReferenceDistCalc.Point endPoint) {
            return base.Channel.distance(startPoint, endPoint);
        }
        
        public System.Threading.Tasks.Task<double> distanceAsync(DistanceCalc.ConsoleClient.ServiceReferenceDistCalc.Point startPoint, DistanceCalc.ConsoleClient.ServiceReferenceDistCalc.Point endPoint) {
            return base.Channel.distanceAsync(startPoint, endPoint);
        }
    }
}
